---
output:
  pdf_document: default
  html_document: default
---
Funciones
---

Listado de funciones básicas y ejemplos

**Unir objetos**

```    
# En columnas: 
cbind(objeto1, objeto2,...)

# En filas:
    
cbind(objeto1, objeto2...)
```

**Mostrar la estructura de un objeto** Número total de variables, tipo de variables, número de casos.

```{r}
str(mtcars)
# Observa que en este caso se trata de un data frame
```

**Visualizar datos o nombres de variables**

```{r}
#Nombrando un objeto, aparece el mismo en la consola, sin embargo para grandes
# sets de datos esto puede ser problemático. Para ello, existe la opción View()
View(mtcars)

# A veces sólo queremos tener una idea de la estructura de los datos visualizando
# las primeras filas
head(mtcars)

# Para conocer el nombre de las variables no es necesario visualizar datos
names(mtcars)
```

**Seleccionar o filtrar** 

```{r}
# Para seleccionar una variable se puede llamar por su nombre
mtcars$mpg # Al seleccionar así, lo que hago es extraer valores del data frame
          # Por lo que cambia el tipo de objeto

# Si no conocemos el nombre pero sí la posición, utilizamos los corchetes
# mtcars[fila, columna]
mtcars[1,3] # Aquí estoy seleccionando el valor que aparece en la primera fila,
            # tercera columna
mtcars[1,] # Selecciono la primera fila entera
mtcars[,8:11] # Selecciono las últimas cuatro columnas
```

**Importar sets de datos de ejemplos**

```{r}
# R cuenta con numerosos sets de datos por defecto. Para cargarlos en tu entorno de 
# trabajo sólo tienes que utilizar la opción data()
data("mtcars") # Aunque se trata de un set de datos, al no ser un objeto precargado 
                # en el entorno de trabajo, deberá estar entrecomillado
```

**Seleccionar subset de datos en función de una condición**

```{r}
# Vamos a seleccionar un subset de datos que incluya únicamente con una cilindrada
# mayor a 4
cilindrada.alta <- subset(mtcars, cyl > 4)
```




